version: "3"
services:
# kafka config from https://github.com/wurstmeister/kafka-docker  
    kafka:
        image: wurstmeister/kafka:2.13-2.7.0
        container_name: kafka
        hostname: kafka
        ports: 
            - "9092:9092"
        environment:
            - DOCKER_API_VERSION: 1.22
            - KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            # note: don't use localhost / 127.0.0.1 if u want to run multiple brokers
            
            # 1 partition, 1 replica, cleanup.policy set to compact
            - KAFKA_CREATE_TOPICS: "cyberse:1:1:compact"
            
            - KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            
    kafka-producer:
        image:
        container_name: kafka-producer
        command: >
                sh -c "pip install -r /usr/src/producer/requirements.txt"
                && python3 /usr/src/producer/kafkaProducerService.py"
    
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        hostname: zookeeper
        ports:
            - "2181:2181"
        networks:
            - cyberse
            
    cassandra:
        image: cassandra:4.0.0
        container_name: cassandra
        hostname: cassandra
        ports:
            - "9042:9042"
        networks:
            - cyberse

networks:
    cyberse:
        driver: bridge